%% CODE TO GENERATE ALL FIGURES IN MONTEIRO, HART AND KACELNIK 2021
% Tiago Monteiro 2021
% all data is available with the paper

%% Figure 1 and Extended figure 1 %% 
% Generates normalised amplitude traces of the stimuli used inthe experiment,
% depicted in Figure 1c,d and Extended figure 1

[shortQuack,Fs] = audioread('naturalShort.wav'); % this should be the naturalShort  stimulus
[longQuack,Fs] = audioread('naturalLong.wav'); % this should be the naturalLong stimulus
[shortNoise,Fs] = audioread('artificialShort.wav'); % this should be the artificialShort stimulus
[longNoise,Fs] = audioread('artificialLong.wav'); % this should be the artificialShort stimulus

info = audioinfo('naturalLong.wav')
t = 0:seconds(1/Fs) : seconds(info.Duration);
t = t(1:end-1);
time = seconds(0:2);

figure ('Name','Monteiro et al. (2021) - sound snippets')
sgtitle('sound stimulus', 'FontSize',36)
subplot(2,2,1)
plot(t(1:length(shortQuack)),shortQuack(:,1), 'color','k')
title('naturalSHORT','fontsize',18)
ylabel('amplitude (normalized)','fontsize',16)
ax = gca;
ax.XAxis.Limits = [time(1) time(3)];
ylim([-1,1])
set(gca,...
        'tickdir','out',...
        'layer','top',...
        'box','off',...
        'linewidth',2,...
        'layer','top',...
        'TickLength',[0 0],...
        'xticklabel',{[]},...
        'yticklabel',{[]});
    
subplot(2,2,2)
plot(t,longQuack(:,1),'color','k')
title('naturalLONG','fontsize',18)
ylim([-1,1])
xlim([t(1) t(end)])

set(gca,...
        'tickdir','out',...
        'layer','top',...
        'box','off',...
        'linewidth',2,...
        'layer','top',...
        'TickLength',[0 0],...
         'xticklabel',{[]},...
        'yticklabel',{[]});
    
subplot(2,2,3)
plot(t(1:length(shortNoise)),shortNoise(:,1),'color','k')
title('artificialSHORT','fontsize',18)
xlabel('time','fontsize',16)
ylabel('amplitude (normalized)','fontsize',16)
ax = gca;
ax.XAxis.Limits = [time(1) time(3)];
ylim([-1,1])
set(gca,...
        'tickdir','out',...
        'layer','top',...
        'box','off',...
        'linewidth',2,...
        'layer','top',...
        'TickLength',[0 0],...
        'yticklabel',{[]});
    
subplot(2,2,4)
plot(t,longNoise(:,1),'color','k')%
title('artificialLONG','fontsize',18)
xlabel('time','fontsize',16)
ylim([-1,1])
xlim([t(1) t(end)])

set(gca,...
        'tickdir','out',...
        'layer','top',...
        'box','off',...
        'linewidth',2,...
        'layer','top',...
        'TickLength',[0 0],...
        'yticklabel',{[]});
    
%% FIGURE 2 and Extended figure 3 %%
% Load data files
prefNatural = readmatrix('preferenceNatural.csv');
prefArtificial = readmatrix('preferenceArtificial.csv');

% parse data and calculate means and SEMs
easyNat = prefNatural(prefNatural(:,4)==1);
int1Nat = prefNatural(prefNatural(:,4)==2);
int2Nat = prefNatural(prefNatural(:,4)==3);
hardNat = prefNatural(prefNatural(:,4)==4);

meanEasyNat = nanmean(easyNat);
meanInt1Nat = nanmean(int1Nat);
meanInt2Nat = nanmean(int2Nat);
meanHardNat = nanmean(hardNat);

SEeasyNat = nanstd(easyNat/sqrt(numel(easyNat)));
SEint1Nat = nanstd(int1Nat/sqrt(numel(int1Nat)));
SEint2Nat = nanstd(int2Nat/sqrt(numel(int2Nat)));
SEhardNat = nanstd(hardNat/sqrt(numel(hardNat)));

easyNatSHORT = prefNatural(prefNatural(:,4)==1 & prefNatural(:,2)==1);
int1NatSHORT = prefNatural(prefNatural(:,4)==2 & prefNatural(:,2)==1);
int2NatSHORT = prefNatural(prefNatural(:,4)==3 & prefNatural(:,2)==1);
hardNatSHORT = prefNatural(prefNatural(:,4)==4 & prefNatural(:,2)==1);

easyNatLONG = prefNatural(prefNatural(:,4)==1 & prefNatural(:,2)==2);
int1NatLONG = prefNatural(prefNatural(:,4)==2 & prefNatural(:,2)==2);
int2NatLONG = prefNatural(prefNatural(:,4)==3 & prefNatural(:,2)==2);
hardNatLONG = prefNatural(prefNatural(:,4)==4 & prefNatural(:,2)==2);

easyArt = prefArtificial(prefArtificial(:,4)==1);
int1Art = prefArtificial(prefArtificial(:,4)==2);
int2Art = prefArtificial(prefArtificial(:,4)==3);
hardArt = prefArtificial(prefArtificial(:,4)==4);

meanEasyArt = nanmean(easyArt);
meanInt1Art = nanmean(int1Art);
meanInt2Art = nanmean(int2Art);
meanHardArt = nanmean(hardArt);

SEeasyArt = nanstd(easyArt/sqrt(numel(easyArt)));
SEint1Art = nanstd(int1Art/sqrt(numel(int1Art)));
SEint2Art = nanstd(int2Art/sqrt(numel(int2Art)));
SEhardArt = nanstd(hardArt/sqrt(numel(hardArt)));

easyArtSHORT = prefArtificial(prefArtificial(:,4)==1 & prefArtificial(:,2)==1);
int1ArtSHORT = prefArtificial(prefArtificial(:,4)==2 & prefArtificial(:,2)==1);
int2ArtSHORT = prefArtificial(prefArtificial(:,4)==3 & prefArtificial(:,2)==1);
hardArtSHORT = prefArtificial(prefArtificial(:,4)==4 & prefArtificial(:,2)==1);

easyArtLONG = prefArtificial(prefArtificial(:,4)==1 & prefArtificial(:,2)==2);
int1ArtLONG = prefArtificial(prefArtificial(:,4)==2 & prefArtificial(:,2)==2);
int2ArtLONG = prefArtificial(prefArtificial(:,4)==3 & prefArtificial(:,2)==2);
hardArtLONG = prefArtificial(prefArtificial(:,4)==4 & prefArtificial(:,2)==2);

% Plot data
colorEASY = [0, 160, 117]/255;
colorINT = [215,95,28]/255;
colorHARD = [117,114,177]/255;

figure ('Name','Monteiro et al. (2021) - Figure 2')
hold on

vEASYnat = [0 -1; 0 1; 2.5 1; 2.5 -1];
vINTnat = [2.5 -1; 2.5 1; 6.5 1; 6.5 -1];
vHARDnat = [6.5 -1; 6.5 1; 9 1; 9 -1];

f = [1 2 3 4];
patch('Faces',f,'Vertices',vEASYnat,'FaceColor',colorEASY, 'FaceAlpha',.1,'HandleVisibility','off')
patch('Faces',f,'Vertices',vINTnat,'FaceColor',colorINT, 'FaceAlpha',.1,'HandleVisibility','off')
patch('Faces',f,'Vertices',vHARDnat,'FaceColor',colorHARD, 'FaceAlpha',.1,'HandleVisibility','off')

plot([2.5,2.5],[-2,2],'-k','linewidth',1.5,'HandleVisibility','off')
plot([4.5,4.5],[-2,2],'-k','linewidth',1.5,'HandleVisibility','off')
plot([6.5,6.5],[-2,2],'-k','linewidth',1.5,'HandleVisibility','off')

plot([0 9],[0 0],'-k','linewidth',1.5,'HandleVisibility','off')

plot([1.5,1.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')
plot([3.5,3.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')
plot([5.5,5.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')
plot([7.5,7.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')

bar(1,meanEasyNat,...
    .75, 'edgecolor','k', 'facecolor','w', 'linewidth',1.5)
bar(3,meanInt1Nat,...
    .75, 'edgecolor','k', 'facecolor','w', 'linewidth',1.5,'HandleVisibility','off')
bar(5,meanInt2Nat,...
    .75, 'edgecolor','k', 'facecolor','w', 'linewidth',1.5,'HandleVisibility','off')
bar(7,meanHardNat,...
    .75, 'edgecolor','k', 'facecolor','w', 'linewidth',1.5,'HandleVisibility','off')

bar(2,meanEasyArt,...
    .75, 'edgecolor','k', 'facecolor','k', 'linewidth',1.5)
bar(4,meanInt1Art,...
    .75, 'edgecolor','k', 'facecolor','k', 'linewidth',1.5,'HandleVisibility','off')
bar(6,meanInt2Art,...
    .75, 'edgecolor','k', 'facecolor','k', 'linewidth',1.5,'HandleVisibility','off')
bar(8,meanHardArt,...
    .75,'edgecolor','k', 'facecolor','k', 'linewidth',1.5,'HandleVisibility','off')

plot([1 1],[(meanEasyNat-SEeasyNat) (meanEasyNat+SEeasyNat)],'-k','linewidth',1.5)
plot([3 3],[(meanInt1Nat-SEint1Nat) (meanInt1Nat+SEint1Nat)],'-k','linewidth',1.5)
plot([5 5],[(meanInt2Nat-SEint2Nat) (meanInt2Nat+SEint2Nat)],'-k','linewidth',1.5)
plot([7 7],[(meanHardNat-SEhardNat) (meanHardNat+SEhardNat)],'-k','linewidth',1.5)

plot([2 2],[(meanEasyArt-SEeasyArt) (meanEasyArt+SEeasyArt)],'-k','linewidth',1.5)
plot([4 4],[(meanInt1Art-SEint1Art) (meanInt1Art+SEint1Art)],'-k','linewidth',1.5)
plot([6 6],[(meanInt2Art-SEint2Art) (meanInt2Art+SEint2Art)],'-k','linewidth',1.5)
plot([8 8],[(meanHardArt-SEhardArt) (meanHardArt+SEhardArt)],'-k','linewidth',1.5)

set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','on',...
    'linewidth',2,...
    'TickLength',[0 0],...
    'xtick',[1.5 3.5 5.5 7.5],...
    'xticklabel',{},...
    'fontsize',14);

legend('natural', 'artificial','location','southeast')
axis square                                                          
xlim([0.5 8.55])
ylim([-.7,.7])
ylabel('Preference index', 'fontsize',20) % 

% Extended figure 3
dummy = nan(40,8);
dummy(1:(length(easyNatSHORT) + length(easyNatLONG)),1) = [easyNatSHORT;easyNatLONG];
dummy(1:(length(easyArtSHORT) + length(easyArtLONG)),2) = [easyArtSHORT;easyArtLONG];
dummy(1:(length(int1NatSHORT) + length(int1NatLONG)),3) = [int1NatSHORT;int1NatLONG];
dummy(1:(length(int1ArtSHORT) + length(int1ArtLONG)),4) = [int1ArtSHORT;int1ArtLONG];
dummy(1:(length(int2NatSHORT) + length(int2NatLONG)),5) = [int2NatSHORT;int2NatLONG];
dummy(1:(length(int2ArtSHORT) + length(int2ArtLONG)),6) = [int2ArtSHORT;int2ArtLONG];
dummy(1:(length(hardNatSHORT) + length(hardNatLONG)),7) = [hardNatSHORT;hardNatLONG];
dummy(1:(length(hardArtSHORT) + length(hardArtLONG)),8) = [hardArtSHORT;hardArtLONG];

s = rng;
N=20;
a=0.8;
b=1.2;
r = a + (b-a).*rand(N,1);
r1 = r; r2 = r1+1; r3=r1+2; r4=r1+3; r5=r1+4; r6=r1+5; r7=r1+6; r8=r1+7;

colorEASY = [0, 160, 117]/255;
colorINT = [215,95,28]/255;
colorHARD = [117,114,177]/255;

figure ('Name','Monteiro et al. (2021) - Extended figure 3')
plot([0 9],[0 0],'--k','linewidth',0.8,'HandleVisibility','off')
hold on

vEASYnat = [0 -3; 0 3; 1.5 3; 1.5 -3];
vINT1nat = [2.5 -3; 2.5 3; 3.5 3; 3.5 -3];
vINT2nat = [4.5 -3; 4.5 3; 5.5 3; 5.5 -3];
vHARDnat = [6.5 -3; 6.5 3; 7.5 3; 7.5 -3];

vEASYart = [1.5 -3; 1.5 3; 2.5 3; 2.5 -3];
vINT1art = [3.5 -3; 3.5 3; 4.5 3; 4.5 -3];
vINT2art = [5.5 -3; 5.5 3; 6.5 3; 6.5 -3];
vHARDart = [7.5 -3; 7.5 3; 8.5 3; 8.5 -3];

f = [1 2 3 4];

plot([1.5,1.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')
plot([3.5,3.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')
plot([5.5,5.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')
plot([7.5,7.5],[-2,2],'--','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')

plot([2.5,2.5],[-3,3],'-k','linewidth',1.5,'HandleVisibility','off')
plot([4.5,4.5],[-3,3],'-k','linewidth',1.5,'HandleVisibility','off')
plot([6.5,6.5],[-3,3],'-k','linewidth',1.5,'HandleVisibility','off')

plot([0 9],[0 0],'-','color',[.5 .5 .5],'linewidth',.8,'HandleVisibility','off')

[h,l,mx,md,bw]=violin([dummy(:,1) dummy(:,2) dummy(:,3) dummy(:,4) dummy(:,5) dummy(:,6) dummy(:,7) dummy(:,8)],...
    'edgecolor',[],'facecolor', [colorEASY;colorEASY;colorINT; colorINT; colorINT; colorINT; colorHARD;colorHARD],...
    'facealpha',.2,'mc',[],'linewidth',.5,'medc',[],'plotlegend',0,...
    'HandleVisibility','off')
legend('off')

plot([.6 1.4], [meanEasyNat meanEasyNat],'-', 'color',colorEASY,'linewidth',7)
plot([2.6 3.4], [meanInt1Nat meanInt1Nat],'-', 'color',colorINT,'linewidth',7)
plot([4.6 5.4], [meanInt2Nat meanInt2Nat],'-', 'color',colorINT,'linewidth',7)
plot([6.6 7.4], [meanHardNat meanHardNat],'-', 'color',colorHARD,'linewidth',7)
plot([.65 1.35], [meanEasyNat meanEasyNat],'-w', 'linewidth',2.5)
plot([2.65 3.35], [meanInt1Nat meanInt1Nat],'-w','linewidth',2.5)
plot([4.65 5.35], [meanInt2Nat meanInt2Nat],'-w','linewidth',2.5)
plot([6.65 7.35], [meanHardNat meanHardNat],'-w','linewidth',2.5)

plot([1.6 2.4], [meanEasyArt meanEasyArt],'-', 'color',colorEASY,'linewidth',7)
plot([3.6 4.4], [meanInt1Art meanInt1Art],'-', 'color',colorINT,'linewidth',7)
plot([5.6 6.4], [meanInt2Art meanInt2Art],'-', 'color',colorINT,'linewidth',7)
plot([7.6 8.4], [meanHardArt meanHardArt],'-', 'color',colorHARD,'linewidth',7)

plot(r1(1:numel(easyNatSHORT)),easyNatSHORT,'o',...
    'MarkerEdgeColor',colorEASY,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1)

plot(r3(1:numel(int1NatSHORT)),int1NatSHORT,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r5(1:numel(int2NatSHORT)),int2NatSHORT,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r7(1:numel(hardNatSHORT)),hardNatSHORT,'o',...
    'MarkerEdgeColor',colorHARD,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r1(1:numel(easyNatLONG)),easyNatLONG,'o',...
    'MarkerEdgeColor',colorEASY,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1)

plot(r3(1:numel(int1NatLONG)),int1NatLONG,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r5(1:numel(int2NatLONG)),int2NatLONG,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r7(1:numel(hardNatLONG)),hardNatLONG,'o',...
    'MarkerEdgeColor',colorHARD,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r2(1:numel(easyArtSHORT)),easyArtSHORT,'o',...
    'MarkerEdgeColor',colorEASY,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r4(1:numel(int1ArtSHORT)),int1ArtSHORT,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r6(1:numel(int2ArtSHORT)),int2ArtSHORT,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r8(1:numel(hardArtSHORT)),hardArtSHORT,'o',...
    'MarkerEdgeColor',colorHARD,...
    'MarkerFaceColor','k',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r2(1:numel(easyArtLONG)),easyArtLONG,'o',...
    'MarkerEdgeColor',colorEASY,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1)

plot(r4(1:numel(int1ArtLONG)),int1ArtLONG,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r6(1:numel(int2ArtLONG)),int2ArtLONG,'o',...
    'MarkerEdgeColor',colorINT,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

plot(r8(1:numel(hardArtLONG)),hardArtLONG,'o',...
    'MarkerEdgeColor',colorHARD,...
    'MarkerFaceColor','w',...
    'MarkerSize',7,...
    'linewidth', 1,'HandleVisibility','off')

int1Label = ['[=dur' '\neq' 'sound]'];
int2Label = ['[' '\neq' 'dur'  '=sound)]'];

ylim([-2 2])
legend('off')
set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','on',...
    'linewidth',2,...
    'TickLength',[0 0],...
    'xtick',[1.5 3.5 5.5 7.5],...
    'xticklabel',{'' int1Label int2Label ''},...
    'fontsize',14);

ylabel('Preference index', 'fontsize',20) % 
axis square

%% Extended figure 2 %%
% plot example trajectories for individual animals

% load data
clear
load('ALLdata.mat')

% top row of the figure (example animals 1-4):

% example #1
expGroup = data.processed.imprinting.natural.short.easy; % select Experimental Group (see readme.txt) 

% plot data
colorRED = [1 0 0];
colorGREEN = [46 139 87]/255;
colorORANGE = [212 139 63]/255;
colorBLUE = [0 0.4470 0.7410];  
colorPINK = [160 32 240]/255;

ii = 11 % corresponds to animal #6 of this group
figure ('Name','Monteiro et al. (2021) - Extended figure 2')
subplot(2,4,1)
hold on
plot(expGroup(:,ii),expGroup(:,ii+1), 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% example #2
expGroup = data.processed.imprinting.natural.short.int1_soundDIFF; % select Experimental Group (see readme.txt) 

ii = 3 % corresponds to animal #2 of this group
subplot(2,4,2)
hold on
plot(expGroup(:,ii)*-1,expGroup(:,ii+1)*-1, 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% example #3
expGroup = data.processed.imprinting.natural.short.int2_timeDIFF; % select Experimental Group (see readme.txt) 

ii = 13 % corresponds to animal #7 of this group 

subplot(2,4,3)
hold on
plot(expGroup(:,ii),expGroup(:,ii+1), 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% example #4
expGroup = data.processed.imprinting.natural.short.hard; % select Experimental Group (see readme.txt) 

ii = 1 % corresponds to animal #1 of this group 

subplot(2,4,4)
hold on
plot(expGroup(:,ii),expGroup(:,ii+1), 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% bottom row of the figure (example animals 5-8)
% example #5
expGroup = data.processed.imprinting.natural.long.easy; % select Experimental Group (see readme.txt) 

ii = 11 % corresponds to animal #6 of this group 

subplot(2,4,5)
hold on
plot(expGroup(:,ii),expGroup(:,ii+1), 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% example #6
expGroup = data.processed.imprinting.natural.long.int1_soundDIFF; % select Experimental Group (see readme.txt) 

ii = 11 % corresponds to animal #6 of this group 

subplot(2,4,6)
hold on
plot(expGroup(:,ii)*-1,expGroup(:,ii+1)*-1, 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% example #7
expGroup = data.processed.imprinting.natural.long.int2_timeDIFF; % select Experimental Group (see readme.txt) 

ii = 39 % corresponds to animal #20 of this group 

subplot(2,4,7)
hold on
plot(expGroup(:,ii),expGroup(:,ii+1), 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);

clear expGroup

% example #8
expGroup = data.processed.imprinting.natural.long.hard; % select Experimental Group (see readme.txt) 

ii = 13 % corresponds to animal #7 of this group 

subplot(2,4,8)
hold on
plot(expGroup(:,ii),expGroup(:,ii+1), 'marker', 'o',...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',3)

plot(-1,0, '.r','markersize', 25)
plot(1,0, '.','color',colorGREEN','markersize', 25)

xlim([-1.2 1.2])
ylim([-1.2 1.2])
axis square

set(gca,...
    'tickdir','out',...
    'layer','bottom',...
    'box','on',...
    'linewidth',3,...
    'TickLength',[0 0],...
    'xticklabel',{[]},...
    'yticklabel',{[]},...
    'fontsize',16);